wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1652467346
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      4: 3.10.4
      5: 0.12.16
      8:
      - 3
      - 5
activation:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 32
composition:
  desc: null
  value: multiplication
data_loading:
  desc: null
  value: 'defaultdict(<class ''list''>, {''train'': [{''selector'': ''/1hop/0qual'',
    ''reify'': False, ''remove_qualifiers'': False, ''loaded'': [{''file'': ''1hop/0qual/train.proto'',
    ''amount'': 3222, ''hash'': ''0e5b2c91fcb4bf46427ad610c87a95b6''}]}], ''validation'':
    [{''selector'': ''/1hop/0qual'', ''reify'': False, ''remove_qualifiers'': False,
    ''loaded'': [{''file'': ''1hop/0qual/validation.proto'', ''amount'': 756, ''hash'':
    ''f6cde06f5ee4b794e784f6a6f9be049c''}]}]})'
data_root:
  desc: null
  value: aifb
dropout:
  desc: null
  value: 0.3
edge_dropout:
  desc: null
  value: 0.0
embedding_dim:
  desc: null
  value: 128
epochs:
  desc: null
  value: 2
graph_pooling:
  desc: null
  value: sum
learning_rate:
  desc: null
  value: 0.001
log_level:
  desc: null
  value: INFO
message_weighting:
  desc: null
  value: symmetric
model_path:
  desc: null
  value: saved\model_AIFB.pt
num_layers:
  desc: null
  value: 2
num_workers:
  desc: null
  value: 0
optimizer:
  desc: null
  value: adam
qualifier_aggregation:
  desc: null
  value: sum
qualifier_composition:
  desc: null
  value: multiplication
repeat_layers_until_diameter:
  desc: null
  value: false
save:
  desc: null
  value: true
similarity:
  desc: null
  value: dotproduct
stop_at_diameter:
  desc: null
  value: false
test_data:
  desc: null
  value: []
train_data:
  desc: null
  value:
  - /1hop/0qual:*
use_bias:
  desc: null
  value: false
use_wandb:
  desc: null
  value: true
validation_data:
  desc: null
  value:
  - /1hop/0qual:*
wandb_group:
  desc: null
  value: null
wandb_name:
  desc: null
  value: null
